// Generated by CoffeeScript 1.9.3
Router.configure({
  loadingTemplate: 'loading',
  layoutTemplate: 'layout'
});

Router.route('/', {
  name: 'home',
  layoutTemplate: 'layout'
});

Router.route('/posts/:_id', {
  name: 'post'
});

Router.route('/allpages', {
  name: 'allpages'
});
